repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry
        language: system
        pass_filenames: true
        args:
          - run
          - --
          - python
          - scripts/run_hook_paths.py
          - python
          - -m
          - black
          - --
        files: \.py$
      - id: ruff
        name: ruff
        entry: poetry
        language: system
        pass_filenames: true
        args:
          - run
          - --
          - python
          - scripts/run_hook_paths.py
          - python
          - -m
          - ruff
          - check
          - --
        files: \.py$
      - id: isort
        name: isort
        entry: poetry
        language: system
        pass_filenames: true
        args:
          - run
          - --
          - python
          - scripts/run_hook_paths.py
          - python
          - -m
          - isort
          - --profile
          - black
          - --
        files: \.py$
